spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/perfumeshopping?serverTimezone=Asia/Taipei
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  mvc:
    path match:
      matching-strategy: ant_path_matcher
debug: true