spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/perfumeshopping?serverTimezone=Asia/Taipei
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    maximum-pool-size: 10
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  mvc:
    path match:
      matching-strategy: ant_path_matcher
debug: true